### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by rezabasiri** [TiankaiHang/Min-SNR-Diffusion-Training#1]
Is it possible to generate images larger than 64x64 using this model? The baseline vit models included for training are only 32 and 64 base and large models, and when --image_size 256 was set, I received a dimension mismatch error.

**Comment by TiankaiHang** [comment]
Hi, @rezabasiri, could you please provide the detailed running command and detailed error information? Thanks.

**Comment by SinanGncgl** [comment]
Yeah, same here. I think you should explicitly mention which pt file is for which model. Because we can not directly run the inference script as it is.

**Comment by TiankaiHang** [comment]
Hi,

You could refer the implementation like this

https://github.com/TiankaiHang/Min-SNR-Diffusion-Training/blob/main/guided_diffusion/vision_transformer.py#L611C2-L628C1

```python
def vit_base_arbitrary(pretrained=False, **kwargs):
    new_kwargs = kwargs
    assert 'img_size' in new_kwargs and 'patch_size' in new_kwargs
    assert new_kwargs['img_size'] % new_kwargs['patch_size'] == 0

    for key in ['embed_dim', 'num_heads', 'mlp_ratio', 'qkv_bias', 'norm_layer']:
        if key in new_kwargs:
            new_kwargs.pop(key)
    if not new_kwargs['class_cond']:
        new_kwargs['num_classes'] = -1
    model = VisionTransformer(
        img_size=new_kwargs['img_size'],
        patch_size=new_kwargs['patch_size'], 
        embed_dim=768, num_heads=12, mlp_ratio=4, qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6), **new_kwargs)
    model.default_cfg = _cfg()
    return model
```

This function supports different image sizes and patch sizes.

If you have further questions, please reopen this issue.

Best.
