### ISSUE TITLE
Inquiry about imagenet 256X256 preparation

### ISSUE THREAD

**Issue by ShiZiqiang** [TiankaiHang/Min-SNR-Diffusion-Training#10]
Good evening, Dr. Hang,

Thank you so much for sharing this excelent work.
Could you please provide some details about the implementation of " imagenet 256X256 preparation"?  Following is my code:

#####################################
from PIL import Image

def crop_image_to_256x256(image_path):
    with Image.open(image_path) as img:
        width, height = img.size
        left = (width - 256)/2
        top = (height - 256)/2
        right = (width + 256)/2
        bottom = (height + 256)/2
        img_cropped = img.crop((left, top, right, bottom))
        return img_cropped

from diffusers import AutoencoderKL

def compress_image_with_autoencoderkl(image):
    # Initialize the AutoencoderKL model
    model_id = "CompVis/autoencoder-kl-stable-diffusion"
    autoencoder = AutoencoderKL.from_pretrained(model_id)

    # Encode and decode the image
    image_tensor = autoencoder.feature_extractor(images=[image], return_tensors="pt").pixel_values
    encoded_images = autoencoder.encode(image_tensor)
    decoded_images = autoencoder.decode(encoded_images)

    return decoded_images

from diffusers import AutoencoderKL

def compress_image_with_autoencoderkl(image):
    # Initialize the AutoencoderKL model
    model_id = "CompVis/autoencoder-kl-stable-diffusion"
    autoencoder = AutoencoderKL.from_pretrained(model_id)

    # Encode and decode the image
    image_tensor = autoencoder.feature_extractor(images=[image], return_tensors="pt").pixel_values
    encoded_images = autoencoder.encode(image_tensor)
    decoded_images = autoencoder.decode(encoded_images)

    return decoded_images
######################33333

I want to be consistency with yours, in order to use your repo. Can you help me to confirm the above code? or can you kindly provide the code of this data preparation for imagenet?
Thank you very much for your time and assistance. I appreciate any reponse.

Best regards,
Ziqiang

**Comment by TiankaiHang** [comment]
i try to find the ooold files 

hope this could help you
```python

def center_crop_arr(pil_image, image_size):
    # We are not on a new enough PIL to support the `reducing_gap`
    # argument, which uses BOX downsampling at powers of two first.
    # Thus, we do it by hand to improve downsample quality.
    while min(*pil_image.size) >= 2 * image_size:
        pil_image = pil_image.resize(
            tuple(x // 2 for x in pil_image.size), resample=Image.BOX
        )

    scale = image_size / min(*pil_image.size)
    pil_image = pil_image.resize(
        tuple(round(x * scale) for x in pil_image.size), resample=Image.BICUBIC
    )

    arr = np.array(pil_image)
    crop_y = (arr.shape[0] - image_size) // 2
    crop_x = (arr.shape[1] - image_size) // 2
    return arr[crop_y : crop_y + image_size, crop_x : crop_x + image_size]


def load_img(path, resolution=128):
    image = Image.open(path).convert("RGB")
    w, h = image.size
    # print(f"loaded input image of size ({w}, {h}) from {path}")
    # w, h = map(lambda x: x - x % 32, (w, h))  # resize to integer multiple of 32
    # image = image.resize((w, h), resample=PIL.Image.LANCZOS)
    # ratio = (resolution + 1) / min(w, h)
    # w, h = int(w * ratio), int(h * ratio)
    # try:
    #     image = image.resize((w, h), resample=PIL.Image.LANCZOS)
    #     image = center_crop(image, resolution=resolution)
    # except:
    #     print(h, w)
    image = center_crop_arr(image, 256)
    
    image = np.array(image).astype(np.float32) / 255.0
    # image = image[None].transpose(0, 3, 1, 2)
    image = image.transpose(2, 0, 1)
    image = torch.from_numpy(image)
    return 2.*image - 1.

```

encoded by the autoencoderkl

```python
model = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse").cuda()
z = model.encode(img).latent_dist.sample()
```

if you have further questions, please reopen the issue

**Comment by ShiZiqiang** [comment]
Thank you so much for the quick response, it really help :)
