### ISSUE TITLE
Compatibility with rescaled betas for zero terminal SNR

### ISSUE THREAD

**Issue by bghira** [TiankaiHang/Min-SNR-Diffusion-Training#2]
Hello, as Bytedance has explained in their paper advocating for zero-terminal SNR, the final sigma value is zero, which leads to a divide by zero using your SNR computation.

I am curious what your proposed solution would be. Mine is to set MSE weight to 1 for these timestamps.

Please advise.

**Comment by markub3327** [comment]
@bghira @TiankaiHang 

Hello,

   there is no issue with division by zero because you must use **the equation for V-objective**. The only question is if the last timestep of diffusion weights 0, then it does not affect the training process of the model. @TiankaiHang, for this case do you think will be better to use a combination of min and max SNR, like max(min(SNR, 5), 1)???

```
betas = cosine_beta_schedule(timesteps)        
alphas = 1.0 - betas
self.alphas_cumprod = np.cumprod(alphas, axis=0)
self.snr = 1.0 / (1 - self.alphas_cumprod) - 1
weight = np.minimum(noise_scheduler.snr, 5) / (noise_scheduler.snr + 1)
```

**For 10 timesteps**:
> alphas_cumprod: [0.97209274 0.89870592 0.78691051 0.64747821 0.49384359 0.34080964
>  0.20312147 0.09404561 0.02409172 0.        ]
> 
> snr: [3.48329659e+01 8.87224531e+00 3.69286404e+00 1.83670409e+00
>  9.75673885e-01 5.17012475e-01 2.54896408e-01 1.03808331e-01
>  2.46864636e-02 0.00000000e+00]
> 
> weight: [0.13953631 0.5064704  0.78691051 0.64747821 0.49384359 0.34080964
>  0.20312147 0.09404561 0.02409172 0.        ]
> 

Thanks.

**Comment by bghira** [comment]
what do you mean? I have directly observed the issue, as has @sayakpaul at HF.

**Comment by markub3327** [comment]
Please look at the last commit at this repo. There is the weight calculation for the V-objective that must be used in combination with zero terminal SNR.

**Comment by bghira** [comment]
ok, my bad. i opened this a month ago and the commit is from 2 days ago and no update was posted here.

as well, i didn't get any credit for the idea of setting the weights to a floor of one.

bad taste about it, i suddenly don't care anymore.

**Comment by bghira** [comment]
also it's correct, the way that is set up, doesn't account for learning on the last timestep. still more work to be done

**Comment by markub3327** [comment]
The paper about zero terminal SNR explains only constant weighting 1. All the next work is for your opinion.

https://arxiv.org/pdf/2305.08891.pdf

**Comment by bghira** [comment]
of course, the idea to combine zero terminal SNR schedule alongside min-SNR was my own.

it's not even supported in other trainers. i was the first. thanks.
